version: "3"

services: 
    app:
        container_name: "cadastro-dev"
        build: .
        volumes:
            - .:/cadastro
            - /tmp/.X11-unix:/tmp/./X11-unix
        environment:
            - DISPLAY=${DISPLAY}
        ports:
        -   "${PORT}:8080"